### ISSUE TITLE
local mp3 file not working

### ISSUE THREAD

**Issue by profispojka** [inos3910/audio-visualizer-by-howlerjs#3]
It seems that the only example that is working is the example with streaming. The local mp3 file does not work. Can this be fixed?

**Comment by inos3910** [comment]
Only demo-4 streaming sound source.
https://inos3910.github.io/audio-visualizer-by-howlerjs/demo-4.html

Others are local sound sources.
https://inos3910.github.io/audio-visualizer-by-howlerjs/
https://inos3910.github.io/audio-visualizer-by-howlerjs/demo-2.html
https://inos3910.github.io/audio-visualizer-by-howlerjs/demo-3.html

I have confirmed all the operations, but they are working.
